#!/usr/bin/env ruby

require 'rubygems'
require 'thor'
require 'fileutils'

module Pvb; end

class Pvb::Cli < Thor
  desc "build BOX", "build image"
  def build(box)
    puts "Building #{box} ..."

    FileUtils.chdir "templates/#{box}" do
      system("packer build -only=virtualbox --force template.json")
    end
  end
end

Pvb::Cli.start(ARGV)
